### ISSUE TITLE
Spelling Mistake in the README

### ISSUE THREAD

**Issue by linchuandai** [GarlandZhang/ar_fps_controller#6]
You have misspelled hands. I hope you can fix this soon. I know you are a busy man. Best you luck!

**Comment by GarlandZhang** [comment]
Wow thanks for letting me know! I will get it fixed as soon as I can. 
Cheers!
~G-Zhang

**Comment by GarlandZhang** [comment]
Updated in commit e67223431e1512ab22589a1116780ffc48595a0e
